name:                transplate-video
version:             0.1.0.0
github:              "githubuser/transplate-video"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/transplate-video#readme>

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - FlexibleInstances
  - TypeApplications
  - RecordWildCards
  - ScopedTypeVariables

  
dependencies:
- base-noprelude >=4.6 && <5
- relude
- ffmpeg-light
- containers
- unordered-containers
- optparse-applicative
- JuicyPixels
- vector

library:
  source-dirs: src

executables:
  transplate-video-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transplate-video

tests:
  transplate-video-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transplate-video
